// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNxqaf9LCMXyhHBIPndqV1EXa8_ds00zo',
    appId: '1:785385039749:web:fb6330d18979608d50c6ec',
    messagingSenderId: '785385039749',
    projectId: 'gymtrack-aa45',
    authDomain: 'gymtrack-aa45.firebaseapp.com',
    storageBucket: 'gymtrack-aa45.appspot.com',
    measurementId: 'G-YSXYQ74NSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLGcEP_bnGwH1MJlGzI8BXkx1QzOYl6VI',
    appId: '1:785385039749:android:7481e9550efc6c3350c6ec',
    messagingSenderId: '785385039749',
    projectId: 'gymtrack-aa45',
    storageBucket: 'gymtrack-aa45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-KDKqX_UIqWo63cZkp8tUnsuo0YYFqPU',
    appId: '1:785385039749:ios:26f3595ed52c443050c6ec',
    messagingSenderId: '785385039749',
    projectId: 'gymtrack-aa45',
    storageBucket: 'gymtrack-aa45.appspot.com',
    androidClientId: '785385039749-75kn0fjbv764hiuv7u99ihvnvsf3t3ti.apps.googleusercontent.com',
    iosClientId: '785385039749-2e4btauja9fsr8ds8fbg3rv98e0imffr.apps.googleusercontent.com',
    iosBundleId: 'aa45.gymtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-KDKqX_UIqWo63cZkp8tUnsuo0YYFqPU',
    appId: '1:785385039749:ios:a78c8679ccc6d27650c6ec',
    messagingSenderId: '785385039749',
    projectId: 'gymtrack-aa45',
    storageBucket: 'gymtrack-aa45.appspot.com',
    androidClientId: '785385039749-75kn0fjbv764hiuv7u99ihvnvsf3t3ti.apps.googleusercontent.com',
    iosClientId: '785385039749-7504h33cu4g4vg4lpfd17gh5jmdojhol.apps.googleusercontent.com',
    iosBundleId: 'aa45.gymtrack.RunnerTests',
  );
}
