// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNxqaf9LCMXyhHBIPndqV1EXa8_ds00zo',
    appId: '1:785385039749:web:05d8857f2ecf602b50c6ec',
    messagingSenderId: '785385039749',
    projectId: 'gymtrack-aa45',
    authDomain: 'gymtrack-aa45.firebaseapp.com',
    storageBucket: 'gymtrack-aa45.appspot.com',
    measurementId: 'G-BZZ1KCW0EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLGcEP_bnGwH1MJlGzI8BXkx1QzOYl6VI',
    appId: '1:785385039749:android:ee8fbc70cbdb63d450c6ec',
    messagingSenderId: '785385039749',
    projectId: 'gymtrack-aa45',
    storageBucket: 'gymtrack-aa45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-KDKqX_UIqWo63cZkp8tUnsuo0YYFqPU',
    appId: '1:785385039749:ios:471d5d14285c733f50c6ec',
    messagingSenderId: '785385039749',
    projectId: 'gymtrack-aa45',
    storageBucket: 'gymtrack-aa45.appspot.com',
    iosClientId: '785385039749-bg2uqchl7bqlra6895qfbeffodqs7bem.apps.googleusercontent.com',
    iosBundleId: 'com.aa45.todo.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-KDKqX_UIqWo63cZkp8tUnsuo0YYFqPU',
    appId: '1:785385039749:ios:64938299d53eb19350c6ec',
    messagingSenderId: '785385039749',
    projectId: 'gymtrack-aa45',
    storageBucket: 'gymtrack-aa45.appspot.com',
    iosClientId: '785385039749-ghi7bcerjgkalj7nmvg8mjra6mqtfl1e.apps.googleusercontent.com',
    iosBundleId: 'com.aa45.todo.todo.RunnerTests',
  );
}
